netty-websocket:
  host: 0.0.0.0
  port: 8128
  path: /conn


spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ins.itstudio.club:3306/instagram?useSSL=false&requireSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong&allowPublicKeyRetrieval=true
    username: root
    password: abcd1234
    hikari:
      idle-timeout: 15000   #
      minimum-idle: 1
      maximum-pool-size: 1

server:
  port: 8088
  servlet:
    context-path: /im
